<?php
include_once('indico_feeds.features.inc');

function indico_feeds_enable() {
    drupal_flush_all_caches();
    drupal_set_message(t('To use the <em>Indico Feeds</em> module, first go to the <a href="@url">Indico Feed Administration</a> to set some general options.', array('@url' => url('admin/structure/feeds/edit/indico/settings/IndicoFetcher'))));
}

function indico_feeds_disable() {
    drupal_flush_all_caches();
}

function indico_feeds_help($path, $arg) {
    switch ($path) {
    case 'admin/help#indico_feeds':
        $output = '';
        $output .= '<h3>' . t('Indico Feeds') . '</h3>';
        $output .= '<p>' . t('This module allows you to import events from Indico. To use it, create a key pair in Indico via <em>My Profile / HTTP API</em>. Then go to the <a href="@fetcher">Indico Fetcher settings</a> and enter your key pair.', array('@fetcher' => url('admin/structure/feeds/edit/indico/settings/IndicoFetcher'))) . '</p>';
        $output .= '<p>' . t('To actually import data from indico, <a href="@feed">create a new <em>Indico Feed</em> content node</a> and enter the requested infomation. To find out the ID of a category, open it in Indico and copy the value of the <em>categId</em> parameter from the URL.', array('@feed' => url('node/add/indico-feed'))) . '</p>';
        return $output;
    }
}

function indico_feeds_feeds_plugins() {
    $info = array();
    $info['IndicoFetcher'] = array(
        'name' => 'Indico Fetcher',
        'description' => 'Fetches indico events.',
        'help' => 'This fetcher retrieves events from Indico.',
        'handler' => array(
            'parent' => 'FeedsFetcher',
            'class' => 'IndicoFetcher',
            'file' => 'indico_feeds.inc',
            'path' => drupal_get_path('module', 'indico_feeds'),
        ),
    );
    $info['IndicoParser'] = array(
        'name' => 'Indico Parser',
        'description' => 'Parses indico events.',
        'help' => 'This parser parses the JSON returned by Indico.',
        'handler' => array(
            'parent' => 'FeedsParser',
            'class' => 'IndicoParser',
            'file' => 'indico_feeds.inc',
            'path' => drupal_get_path('module', 'indico_feeds'),
        ),
    );
    return $info;
}
