<?php
include_once('indico_feeds.features.inc');

function indico_feeds_enable() {
    // Enable all indico importers (in case some already exist).
    $disabled = array();
    foreach(feeds_importer_load_all(true) as $importer) {
        $disabled[$importer->id] = _indico_feeds_is_indico_importer($importer) ? false : $importer->disabled;
    }
    variable_set('default_feeds_importer', $disabled);
    feeds_cache_clear();

    // Ensure our fields are up to date
    field_features_rebuild('indico_feeds');

    // Clear all caches and tell users what to do next
    drupal_flush_all_caches();
    drupal_set_message(t('To use the <em>Indico Feeds</em> module, first go to the <a href="@url">Indico Feed Administration</a> to set some general options.', array('@url' => url('admin/structure/feeds/edit/indico/settings/IndicoFetcher'))));
}

function indico_feeds_disable() {
    // Disable all indico importers
    $disabled = array();
    foreach(feeds_importer_load_all(true) as $importer) {
        $disabled[$importer->id] = _indico_feeds_is_indico_importer($importer) ? true : $importer->disabled;
    }
    variable_set('default_feeds_importer', $disabled);
    feeds_cache_clear();

    // Clear all caches just to be safe
    drupal_flush_all_caches();
}

function _indico_feeds_is_indico_importer($importer) {
    $cfg = $importer->getConfig();
    return ($cfg['fetcher']['plugin_key'] == 'IndicoFetcher' || $cfg['parser']['plugin_key'] == 'IndicoParser');
}

function indico_feeds_help($path, $arg) {
    switch ($path) {
    case 'admin/help#indico_feeds':
        $output = '';
        $output .= '<h3>' . t('Indico Feeds') . '</h3>';
        $output .= '<p>' . t('This module allows you to import events from Indico. To use it, create a key pair in Indico via <em>My Profile / HTTP API</em>. Then go to the <a href="@fetcher">Indico Fetcher settings</a> and enter your key pair.', array('@fetcher' => url('admin/structure/feeds/edit/indico/settings/IndicoFetcher'))) . '</p>';
        $output .= '<p>' . t('To actually import data from indico, <a href="@feed">create a new <em>Indico Feed</em> content node</a> and enter the requested infomation. To find out the ID of a category, open it in Indico and copy the value of the <em>categId</em> parameter from the URL.', array('@feed' => url('node/add/indico-feed'))) . '</p>';
        return $output;
    }
}

function indico_feeds_feeds_plugins() {
    $info = array();
    $info['IndicoFetcher'] = array(
        'name' => 'Indico Fetcher',
        'description' => 'Fetches indico events.',
        'help' => 'This fetcher retrieves events from Indico.',
        'handler' => array(
            'parent' => 'FeedsFetcher',
            'class' => 'IndicoFetcher',
            'file' => 'indico_feeds.inc',
            'path' => drupal_get_path('module', 'indico_feeds'),
        ),
    );
    $info['IndicoParser'] = array(
        'name' => 'Indico Parser',
        'description' => 'Parses indico events.',
        'help' => 'This parser parses the JSON returned by Indico.',
        'handler' => array(
            'parent' => 'FeedsParser',
            'class' => 'IndicoParser',
            'file' => 'indico_feeds.inc',
            'path' => drupal_get_path('module', 'indico_feeds'),
        ),
    );
    return $info;
}

function indico_feeds_date_format_types() {
    return array(
        'indico_feeds_event_time' => t('Short event time'),
    );
}

function indico_feeds_date_formats() {
    return array(
        array(
            'type' => 'indico_feeds_event_time',
            'format' => 'H:i',
        ),
        array(
            'type' => 'indico_feeds_event_time',
            'format' => 'g:ia',
        ),
    );
}
